"""
core/types package

This package contains type definitions for various components of the project.
"""

from .agent_config import AgentConfig
from .models import (
    # Predefined model configurations
    CLAUDE_BASIC,
    CLAUDE_FABLE_5,
    CLAUDE_SONNET_5,
    CLAUDE_SONNET_5_WITH_REASONING,
    CLAUDE_WITH_REASONING,
    DEEPSEEK_CHAT,
    DEEPSEEK_REASONER,
    DEEPSEEK_V4_FLASH,
    DEEPSEEK_V4_FLASH_NON_REASONING,
    DEEPSEEK_V4_PRO,
    DEEPSEEK_V4_PRO_MAX,
    DEEPSEEK_V4_PRO_NON_REASONING,
    GEMINI_3_1_FLASH_LITE,
    GEMINI_3_1_PRO_PREVIEW,
    GEMINI_3_5_FLASH,
    GEMINI_3_FLASH_PREVIEW,
    GEMINI_3_PRO_PREVIEW,
    GEMINI_FLASH,
    GEMINI_FLASH_DYNAMIC,
    GEMINI_PRO,
    GPT4_1_CREATIVE,
    GPT4_1_DEFAULT,
    GPT4_1_PRECISE,
    O3_HIGH,
    O3_LOW,
    O3_MEDIUM,
    O4_MINI_HIGH,
    O4_MINI_LOW,
    O4_MINI_MEDIUM,
    ModelConfig,
    create_researcher_config,
)

__all__ = [
    "AgentConfig",
    "CLAUDE_BASIC",
    "CLAUDE_FABLE_5",
    "CLAUDE_SONNET_5",
    "CLAUDE_SONNET_5_WITH_REASONING",
    "CLAUDE_WITH_REASONING",
    "DEEPSEEK_CHAT",
    "DEEPSEEK_REASONER",
    "DEEPSEEK_V4_FLASH",
    "DEEPSEEK_V4_FLASH_NON_REASONING",
    "DEEPSEEK_V4_PRO",
    "DEEPSEEK_V4_PRO_MAX",
    "DEEPSEEK_V4_PRO_NON_REASONING",
    "GEMINI_3_1_FLASH_LITE",
    "GEMINI_3_1_PRO_PREVIEW",
    "GEMINI_3_5_FLASH",
    "GEMINI_3_FLASH_PREVIEW",
    "GEMINI_3_PRO_PREVIEW",
    "GEMINI_FLASH",
    "GEMINI_FLASH_DYNAMIC",
    "GEMINI_PRO",
    "GPT4_1_CREATIVE",
    "GPT4_1_DEFAULT",
    "GPT4_1_PRECISE",
    "O3_HIGH",
    "O3_LOW",
    "O3_MEDIUM",
    "O4_MINI_HIGH",
    "O4_MINI_LOW",
    "O4_MINI_MEDIUM",
    "ModelConfig",
    "create_researcher_config",
]
